---
schedule:

  # Kitchen
  # =======
  - unit: kitchen_window
    events:

      - on: weekdays
        turn_on:
          - '07:00'
          - '18:30'
        turn_off:
          - '08:00'
          - '22:15'

      - on: weekends
        turn_on:  '18:30'
        turn_off: '22:15'

  # Living room
  # =======
  - unit: living_room_window
    events:

      - on: weekdays
        turn_on:  '18:30'
        turn_off: '23:00'

      - on: weekends
        turn_on:  '18:30'
        turn_off: '23:30'

  - unit: living_room_corner
    events:

      - on: weekdays
        turn_on:  '18:30'
        turn_off: '23:00'

      - on: weekends
        turn_on:  '18:30'
        turn_off: '23:30'

  - unit: hallway_lamp
    events:

      - on: weekdays
        turn_on:  '18:30'
        turn_off: '23:00'

      - on: weekends
        turn_on:  '18:30'
        turn_off: '23:30'

  - unit: bedside_lamp
    events:

      - on: weekdays
        turn_on:  '06:55'
        turn_off: '07:30'


      - on: weekends
        turn_on:  '09:00'
        turn_off: '11:00'


vacation:
  - 2018-06-06

timezone: Europe/Stockholm
executable: /var/radio/bin/radio
remotes:
  - 0x65a5a969659a9450
  - 0x69a65a55565a9450
  - 0x69a595aa559a9450
protocol:
  on_code:  0x200
  off_code: 0x100
  unit_codes:
    - 0x5
    - 0x6
    - 0x9
units:
  kitchen_window:
    label: Kitchen Window
    remote: 1
    i: 0
  living_room_window:
    label: Living Room Window Lights
    remote: 1
    i: 1
  living_room_corner:
    label: Living Room Paper Lamp
    remote: 1
    i: 2
  hallway_lamp:
    label: Hallway Lamp
    remote: 2
    i: 0
  bedside_lamp:
    label: Bedside Lamp
    remote: 2
    i: 1
...
