---
schedule:

  # Kitchen
  # =======
  - unit: kitchen_window
    events:

      - on: weekdays
        turn_on:  '07:10'
        turn_off: '07:56'

  # Living room
  # =======
  - unit: living_room_window
    events:

      - on: weekdays
        turn_on:  '17:51'
        turn_off: '21:52'

      - on: weekends
        turn_on:  '17:52'
        turn_off: '22:53'

vacation:
  - 2018-06-06

timezone: Europe/Stockholm
executable: /var/radio/bin/radio
remotes:
  - 0x65a5a969659a9450
  - 0x69a65a55565a9450
  - 0x69a595aa559a9450
protocol:
  on_code:  0x200
  off_code: 0x100
  unit_codes:
    - 0x5
    - 0x6
    - 0x9
units:
  kitchen_window:
    remote: 2
    i: 1
  living_room_window:
    remote: 2
    i: 2
...
